export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USERNAME = "LOGIN_USERNAME";
export const ADD_LIKES = "ADD_LIKES";
export const ADD_DISLIKES = "ADD_DISLIKES";
export const ADD_RECOMMENDATIONS = "ADD_RECOMMENDATIONS";
